# 应用名称
spring:
  application:
    name: user-consumer
  # 默认 Ribbon 重试机制为 true 开启
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
# 应用服务 WEB 访问端口
server:
  port: ${PORT}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

# Actuator Web 访问端口

# Ribbon 配置
ribbon:
  #连接超时时间(ms)
  ConnectTimeout: 1000
  # 业务逻辑超时时间(ms)
  ReadTimeout: 2000

# Feign 配置
feign:
  hystrix:
    # 开启 Feign 的 Hystrix
    enabled: true
