# 应用名称
spring:
  application:
    name: user-provider
    # zipkin 配置
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      rate: 1
# 应用服务 WEB 访问端口
server:
  port: ${PORT}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
